orqueio.bpm:
  metrics:
    enabled: false
    db-reporter-activate: false
  rest-api:
    basic-auth-enabled: false

spring:
  main.allow-bean-definition-overriding: true
  security.user: 
    name: demo
    password: demo